[mypy]
plugins = mypy_django_plugin.main
python_version = 3.13
mypy_path = .
explicit_package_bases = True
warn_unused_ignores = True
show_error_codes = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings

[mypy-apps.*]
disallow_untyped_defs = False

[mypy-config.*]
disallow_untyped_defs = False

[mypy-*.migrations.*]
ignore_errors = True

[mypy-silk.*]
ignore_missing_imports = True
