# Generated by Django 6.1.1 on 2026-09-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exceptions', '0002_exceptionrecord_paired_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('resolved_exception', 'Resolved exception'), ('policy', 'Policy / playbook')], default='resolved_exception', max_length=40)),
                ('project_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(help_text='Retrieval document (no raw PII payloads).')),
                ('embedding', models.JSONField(default=list, help_text='Dense vector stored as JSON (pgvector optional later).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_chunk', to='exceptions.exceptionrecord')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
