# Generated by Django 6.1.1 on 2026-09-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text="Adapter type name (e.g., 'csv', 'rest_api')", max_length=50)),
                ('source_id', models.CharField(db_index=True, help_text='Identifier for the source dataset/file', max_length=100)),
                ('raw_payload', models.JSONField(help_text='Untouched raw payload dictionary')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', help_text='Processing status (PENDING, NORMALIZED, ERROR)', max_length=20)),
            ],
            options={
                'verbose_name': 'Raw Record',
                'verbose_name_plural': 'Raw Records',
                'ordering': ['-ingested_at'],
            },
        ),
    ]
