# Generated by Django 6.1.1 on 2026-09-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_sourcedefinition_sourcefilespec'),
        ('ingestion', '0005_ingestfile_fk_rawrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestfile',
            name='connector_fetch_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ingestfile',
            name='source_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_files', to='connectors.sourcedefinition'),
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='connectors.sourcedefinition')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='ingestion.mappingtemplate')),
            ],
            options={
                'ordering': ['-last_run_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingestion.ingestionjob')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_path', models.CharField(max_length=500)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('fetched', 'Fetched'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('ingest_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_files', to='ingestion.ingestfile')),
                ('source_file_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectors.sourcefilespec')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_files', to='ingestion.ingestionjobrun')),
            ],
        ),
        migrations.AddField(
            model_name='ingestfile',
            name='job_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_files', to='ingestion.ingestionjobrun'),
        ),
    ]
