# Generated by Django 6.1.1 on 2026-09-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_sourcedefinition_sourcefilespec'),
        ('ingestion', '0006_ingestfile_connector_fetch_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestionjob',
            name='source',
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='connectors.connector'),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='default_source_type',
            field=models.CharField(default='csv', max_length=50),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='profile_local_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='source_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='connectors.sourcedefinition'),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='source_id',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to run')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='ingestionjobrun',
            name='primary_ingest_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_job_run', to='ingestion.ingestfile'),
        ),
        migrations.CreateModel(
            name='IngestionJobInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('remote_path', models.CharField(blank=True, default='', max_length=500)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ingestion.ingestionjob')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
