# Generated by Django 6.1.1 on 2026-09-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
        ('ingestion', '0005_ingestfile_fk_rawrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('default_source_type', models.CharField(default='csv', max_length=50)),
                ('file_selection_mode', models.CharField(choices=[('explicit_paths', 'Explicit file paths'), ('glob', 'Glob (future)'), ('postgres_query', 'Postgres query (future)')], default='explicit_paths', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='connectors.connector')),
                ('mapping_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_definitions', to='ingestion.mappingtemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceFileSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('remote_path', models.CharField(max_length=500)),
                ('glob_pattern', models.CharField(blank=True, default='', max_length=200)),
                ('postgres_query', models.TextField(blank=True, default='')),
                ('filename_hint', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_specs', to='connectors.sourcedefinition')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'remote_path'), name='uniq_source_remote_path')],
            },
        ),
    ]
