# Generated by Django 6.1.1 on 2026-09-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reconciliation', '0004_matchrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=10)),
                ('reason', models.CharField(default='unmatched', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('ai_suggestion', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='reconciliation.reconproject')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='reconciliation.reconrun')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_records', to='reconciliation.transaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
