# Generated by Django 6.1.1 on 2026-09-15 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0001_initial'),
        ('reconciliation', '0004_matchrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionrecord',
            name='paired_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_manual_pairs', to='reconciliation.transaction'),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='resolution_kind',
            field=models.CharField(blank=True, choices=[('manual_match', 'Manual match'), ('write_off', 'Write-off'), ('rejected', 'Rejected')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceptionrecord',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exceptionrecord',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
    ]
