# Generated by Django 6.1.1 on 2026-09-13 00:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, help_text='Source identifier', max_length=100)),
                ('external_ref', models.CharField(db_index=True, help_text='Upstream reference ID', max_length=100)),
                ('cr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (>= 0.00)', max_digits=18)),
                ('dr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (>= 0.00)', max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed net amount (credit positive, debit negative)', max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict, help_text='Original raw record payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source_id', 'external_ref'], name='reconciliat_source__f6ce0b_idx'), models.Index(fields=['timestamp', 'amount'], name='reconciliat_timesta_2f7e4c_idx')],
            },
        ),
    ]
