# Generated by Django 6.1.1 on 2026-09-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_ingestfile_fk_rawrecord'),
        ('reconciliation', '0002_transaction_ingest_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reconciliation.reconproject')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('rule_name', models.CharField(default='exact_1_1', max_length=80)),
                ('status', models.CharField(choices=[('matched', 'Matched')], default='matched', max_length=20)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('source_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results_as_source', to='reconciliation.transaction')),
                ('target_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results_as_target', to='reconciliation.transaction')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconciliation.reconrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReconLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('source', 'Source'), ('target', 'Target')], max_length=10)),
                ('feed_key', models.CharField(help_text='Copy of ingest source_id for display', max_length=100)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('ingest_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.ingestfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='reconciliation.reconproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'role'), name='uniq_recon_leg_role_per_project')],
            },
        ),
    ]
