# Generated by Django 6.1.1 on 2026-09-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0003_recon_phase_5a'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower runs first.')),
                ('cardinality', models.CharField(choices=[('one_to_one', '1:1')], default='one_to_one', max_length=20)),
                ('action', models.CharField(choices=[('mark_matched', 'Mark as match')], default='mark_matched', max_length=30)),
                ('logic_mode', models.CharField(choices=[('simple', 'Simple'), ('if_else', 'If / else')], default='simple', max_length=20)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='reconciliation.reconproject')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
