# Generated by Django 6.1.1 on 2026-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_matchrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_filename',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Originating file when multiple files were merged in one ingestion job.', max_length=255),
        ),
    ]
